const { contextBridge, ipcRenderer } = require("electron");

function subscribe(channel) {
  return (callback) => {
    const listener = (_event, payload) => callback(payload);
    ipcRenderer.on(channel, listener);
    return () => ipcRenderer.removeListener(channel, listener);
  };
}

contextBridge.exposeInMainWorld("agzosDesktop", {
  attachTab: (id, url, options) => ipcRenderer.invoke("tab:attach", { id, url, options }),
  activateTab: (id) => ipcRenderer.invoke("tab:activate", { id }),
  setBounds: (rect, id) => ipcRenderer.invoke("tab:bounds", rect, id),
  setSplit: (ids) => ipcRenderer.invoke("tab:split", ids),
  sidePanelShow: (app, url) => ipcRenderer.invoke("sidepanel:show", { app, url }),
  sidePanelHide: () => ipcRenderer.invoke("sidepanel:hide"),
  sidePanelBounds: (rect) => ipcRenderer.invoke("sidepanel:bounds", rect),
  sidePanelReload: (app) => ipcRenderer.invoke("sidepanel:reload", { app }),
  sidePanelUnload: (app) => ipcRenderer.invoke("sidepanel:unload", { app }),
  navigate: (id, url) => ipcRenderer.invoke("tab:navigate", { id, url }),
  goBack: (id) => ipcRenderer.invoke("tab:back", { id }),
  goForward: (id) => ipcRenderer.invoke("tab:forward", { id }),
  reload: (id, ignoreCache = false) => ipcRenderer.invoke("tab:reload", { id, ignoreCache }),
  snapshotTab: (id) => ipcRenderer.invoke("tab:snapshot", { id }),
  captureTab: (id) => ipcRenderer.invoke("tab:capture", { id }),
  zoom: (id, direction) => ipcRenderer.invoke("tab:zoom", { id, direction }),
  findStart: (id, text, options) =>
    ipcRenderer.invoke("find:start", {
      id,
      text,
      forward: options?.forward !== false,
      newSession: Boolean(options?.newSession),
    }),
  findStop: (id) => ipcRenderer.invoke("find:stop", { id }),
  toggleFullscreen: () => ipcRenderer.invoke("window:toggle-fullscreen"),
  adblockConfig: (config) => ipcRenderer.invoke("adblock:config", config),
  adblockStats: () => ipcRenderer.invoke("adblock:stats"),
  adblockUpdate: () => ipcRenderer.invoke("adblock:update"),
  downloadsList: () => ipcRenderer.invoke("downloads:list"),
  downloadAction: (id, action) => ipcRenderer.invoke("download:action", { id, action }),
  downloadsClear: () => ipcRenderer.invoke("downloads:clear"),
  downloadsDir: () => ipcRenderer.invoke("downloads:dir"),
  openDownloadsDir: () => ipcRenderer.invoke("downloads:open-dir"),
  quitApp: () => ipcRenderer.invoke("app:quit"),
  closeTab: (id) => ipcRenderer.invoke("tab:close", { id }),
  muteTab: (id, muted) => ipcRenderer.invoke("tab:mute", { id, muted }),
  setPanelOpen: (open) => ipcRenderer.invoke("chrome:panel", { open }),
  showTabMenu: (context) => ipcRenderer.invoke("tabmenu:show", context),
  respondPermission: (id, allow, remember) =>
    ipcRenderer.invoke("permission:respond", { id, allow, remember }),
  stateLoad: () => ipcRenderer.invoke("state:load"),
  stateSave: (sections) => ipcRenderer.invoke("state:save", sections),
  keyLoad: () => ipcRenderer.invoke("key:load"),
  keySave: (list) => ipcRenderer.invoke("key:save", list),
  agzosKeyState: () => ipcRenderer.invoke("agzosKey:state"),
  agzosKeyPair: (pairingCode, deviceName) =>
    ipcRenderer.invoke("agzosKey:pair", { pairingCode, deviceName }),
  agzosKeyUnlock: (masterPassword) => ipcRenderer.invoke("agzosKey:unlock", { masterPassword }),
  agzosKeyLock: () => ipcRenderer.invoke("agzosKey:lock"),
  agzosKeyList: () => ipcRenderer.invoke("agzosKey:list"),
  agzosKeySave: (entry) => ipcRenderer.invoke("agzosKey:save", entry),
  agzosKeyRemove: (id) => ipcRenderer.invoke("agzosKey:remove", { id }),
  agzosKeyUnpair: () => ipcRenderer.invoke("agzosKey:unpair"),
  autofill: (id, username, password) =>
    ipcRenderer.invoke("tab:autofill", { id, username, password }),
  openExternal: (url) => ipcRenderer.invoke("shell:openExternal", url),
  permissionsList: () => ipcRenderer.invoke("permissions:list"),
  permissionsSet: (origin, type, value) =>
    ipcRenderer.invoke("permissions:set", { origin, type, value }),
  permissionsReset: (origin) => ipcRenderer.invoke("permissions:reset", { origin }),
  historyList: (query) => ipcRenderer.invoke("history:list", query ?? {}),
  historySearch: (text, limit) => ipcRenderer.invoke("history:search", { text, limit }),
  historyDelete: (ids) => ipcRenderer.invoke("history:delete", { ids }),
  historyDeleteUrl: (url) => ipcRenderer.invoke("history:delete-url", { url }),
  historyClear: (range) => ipcRenderer.invoke("history:clear", range ?? {}),
  suggest: (engine, text) => ipcRenderer.invoke("omnibox:suggest", { engine, text }),
  showMenu: (items) => ipcRenderer.invoke("menu:show", items),
  updateState: () => ipcRenderer.invoke("update:state"),
  updateCheck: () => ipcRenderer.invoke("update:check"),
  updateInstall: () => ipcRenderer.invoke("update:install"),
  newWindow: (options) => ipcRenderer.invoke("window:new", options ?? {}),
  moveTabToWindow: (id, tab) => ipcRenderer.invoke("tab:move-to-window", { id, tab }),
  syncTabs: (ids) => ipcRenderer.invoke("tabs:known", { ids }),
  pictureInPicture: (id) => ipcRenderer.invoke("tab:pip", { id }),
  hibernateTab: (id) => ipcRenderer.invoke("tab:hibernate", { id }),
  killTab: (id) => ipcRenderer.invoke("tab:kill", { id }),
  allowCertificate: (id) => ipcRenderer.invoke("certificate:allow", { id }),
  windowStartup: () => ipcRenderer.invoke("window:startup"),
  whatsNew: () => ipcRenderer.invoke("app:whats-new"),
  appVersion: () => ipcRenderer.invoke("app:version"),
  onStateSync: subscribe("agzos:state-sync"),
  onUpdate: subscribe("agzos:update"),
  onTabEvent: subscribe("agzos:tab-event"),
  onOpenRequest: subscribe("agzos:open-request"),
  onFullscreen: subscribe("agzos:fullscreen"),
  onHotkey: subscribe("agzos:hotkey"),
  onTabMenuAction: subscribe("agzos:tabmenu-action"),
  onRequestPermission: subscribe("agzos:permission-request"),
  onDownload: subscribe("agzos:download"),
  onModifierUp: subscribe("agzos:modifier-up"),
  showTabPreview: (payload) => ipcRenderer.invoke("preview:show", payload),
  hideTabPreview: () => ipcRenderer.invoke("preview:hide"),
  renderSwitcher: (model) => ipcRenderer.invoke("switcher:render", model),
  setSwitcherOpen: (open) => ipcRenderer.invoke("switcher:state", { open }),
  onSwitcherKey: subscribe("agzos:switcher-key"),
  onAdblockStats: subscribe("agzos:adblock-stats"),
  overlayOpen: (payload) => ipcRenderer.invoke("overlay:open", payload),
  overlayClose: () => ipcRenderer.invoke("overlay:close"),
  overlayReply: (id, result) => ipcRenderer.invoke("overlay:reply", { id, result }),
  onOverlayCall: subscribe("agzos:overlay-call"),
  onOverlayDismissed: subscribe("agzos:overlay-dismissed"),
});
