const { contextBridge, ipcRenderer } = require("electron");

function subscribe(channel) {
  return (callback) => {
    const listener = (_event, payload) => callback(payload);
    ipcRenderer.on(channel, listener);
    return () => ipcRenderer.removeListener(channel, listener);
  };
}

contextBridge.exposeInMainWorld("agzosDesktop", {
  attachTab: (id, url, options) => ipcRenderer.invoke("tab:attach", { id, url, options }),
  activateTab: (id) => ipcRenderer.invoke("tab:activate", { id }),
  setBounds: (rect, id) => ipcRenderer.invoke("tab:bounds", rect, id),
  setSplit: (ids) => ipcRenderer.invoke("tab:split", ids),
  sidePanelShow: (app, url) => ipcRenderer.invoke("sidepanel:show", { app, url }),
  sidePanelHide: () => ipcRenderer.invoke("sidepanel:hide"),
  sidePanelBounds: (rect) => ipcRenderer.invoke("sidepanel:bounds", rect),
  sidePanelReload: (app) => ipcRenderer.invoke("sidepanel:reload", { app }),
  sidePanelUnload: (app) => ipcRenderer.invoke("sidepanel:unload", { app }),
  sidePanelZoom: (app, direction) => ipcRenderer.invoke("sidepanel:zoom", { app, direction }),
  sidePanelZoomGet: (app) => ipcRenderer.invoke("sidepanel:zoom-get", { app }),
  sidePanelDrag: (active) => ipcRenderer.invoke("sidepanel:drag", { active }),
  onSidePanelZoom: subscribe("agzos:side-panel-zoom"),
  onSidePanelDrag: subscribe("agzos:side-panel-drag"),
  navigate: (id, url) => ipcRenderer.invoke("tab:navigate", { id, url }),
  goBack: (id) => ipcRenderer.invoke("tab:back", { id }),
  goForward: (id) => ipcRenderer.invoke("tab:forward", { id }),
  reload: (id, ignoreCache = false) => ipcRenderer.invoke("tab:reload", { id, ignoreCache }),
  snapshotTab: (id) => ipcRenderer.invoke("tab:snapshot", { id }),
  captureTab: (id) => ipcRenderer.invoke("tab:capture", { id }),
  zoom: (id, direction) => ipcRenderer.invoke("tab:zoom", { id, direction }),
  findStart: (id, text, options) =>
    ipcRenderer.invoke("find:start", {
      id,
      text,
      forward: options?.forward !== false,
      newSession: Boolean(options?.newSession),
    }),
  findStop: (id) => ipcRenderer.invoke("find:stop", { id }),
  toggleFullscreen: () => ipcRenderer.invoke("window:toggle-fullscreen"),
  adblockConfig: (config) => ipcRenderer.invoke("adblock:config", config),
  adblockStats: () => ipcRenderer.invoke("adblock:stats"),
  adblockUpdate: () => ipcRenderer.invoke("adblock:update"),
  downloadsList: () => ipcRenderer.invoke("downloads:list"),
  downloadAction: (id, action) => ipcRenderer.invoke("download:action", { id, action }),
  downloadsClear: () => ipcRenderer.invoke("downloads:clear"),
  downloadsDir: () => ipcRenderer.invoke("downloads:dir"),
  openDownloadsDir: () => ipcRenderer.invoke("downloads:open-dir"),
  quitApp: () => ipcRenderer.invoke("app:quit"),
  closeTab: (id) => ipcRenderer.invoke("tab:close", { id }),
  muteTab: (id, muted) => ipcRenderer.invoke("tab:mute", { id, muted }),
  setPanelOpen: (open) => ipcRenderer.invoke("chrome:panel", { open }),
  showTabMenu: (context) => ipcRenderer.invoke("tabmenu:show", context),
  respondPermission: (id, allow, remember) =>
    ipcRenderer.invoke("permission:respond", { id, allow, remember }),
  stateLoad: () => ipcRenderer.invoke("state:load"),
  stateSave: (sections) => ipcRenderer.invoke("state:save", sections),
  keyLoad: () => ipcRenderer.invoke("key:load"),
  keySave: (list) => ipcRenderer.invoke("key:save", list),
  agzosKeyState: () => ipcRenderer.invoke("agzosKey:state"),
  agzosKeyPair: (pairingCode, deviceName) =>
    ipcRenderer.invoke("agzosKey:pair", { pairingCode, deviceName }),
  agzosKeyUnlock: (masterPassword) => ipcRenderer.invoke("agzosKey:unlock", { masterPassword }),
  agzosKeyLock: () => ipcRenderer.invoke("agzosKey:lock"),
  agzosKeyList: () => ipcRenderer.invoke("agzosKey:list"),
  agzosKeySave: (entry) => ipcRenderer.invoke("agzosKey:save", entry),
  agzosKeyRemove: (id) => ipcRenderer.invoke("agzosKey:remove", { id }),
  agzosKeyUnpair: () => ipcRenderer.invoke("agzosKey:unpair"),
  autofill: (id, username, password) =>
    ipcRenderer.invoke("tab:autofill", { id, username, password }),
  autofillOtp: (id, code) => ipcRenderer.invoke("tab:autofill-otp", { id, code }),
  loginFields: (id) => ipcRenderer.invoke("tab:login-fields", { id }),
  openExternal: (url) => ipcRenderer.invoke("shell:openExternal", url),
  permissionsList: () => ipcRenderer.invoke("permissions:list"),
  permissionsSet: (origin, type, value) =>
    ipcRenderer.invoke("permissions:set", { origin, type, value }),
  permissionsReset: (origin) => ipcRenderer.invoke("permissions:reset", { origin }),
  historyList: (query) => ipcRenderer.invoke("history:list", query ?? {}),
  historySearch: (text, limit) => ipcRenderer.invoke("history:search", { text, limit }),
  historyDelete: (ids) => ipcRenderer.invoke("history:delete", { ids }),
  historyDeleteUrl: (url) => ipcRenderer.invoke("history:delete-url", { url }),
  historyClear: (range) => ipcRenderer.invoke("history:clear", range ?? {}),
  suggest: (engine, text) => ipcRenderer.invoke("omnibox:suggest", { engine, text }),
  showMenu: (items) => ipcRenderer.invoke("menu:show", items),
  updateState: () => ipcRenderer.invoke("update:state"),
  updateCheck: () => ipcRenderer.invoke("update:check"),
  updateInstall: () => ipcRenderer.invoke("update:install"),
  newWindow: (options) => ipcRenderer.invoke("window:new", options ?? {}),
  moveTabToWindow: (id, tab) => ipcRenderer.invoke("tab:move-to-window", { id, tab }),
  syncTabs: (ids) => ipcRenderer.invoke("tabs:known", { ids }),
  pictureInPicture: (id) => ipcRenderer.invoke("tab:pip", { id }),
  hibernateTab: (id) => ipcRenderer.invoke("tab:hibernate", { id }),
  killTab: (id) => ipcRenderer.invoke("tab:kill", { id }),
  gxStats: () => ipcRenderer.invoke("gx:stats"),
  gxSpeedTest: () => ipcRenderer.invoke("gx:speedtest"),
  gxCacheSize: () => ipcRenderer.invoke("gx:cache-size"),
  gxClearCache: () => ipcRenderer.invoke("gx:clear-cache"),
  aiState: () => ipcRenderer.invoke("ai:state"),
  aiSetKey: (key) => ipcRenderer.invoke("ai:set-key", { key }),
  aiRemoveKey: () => ipcRenderer.invoke("ai:remove-key"),
  aiModels: (refresh) => ipcRenderer.invoke("ai:models", { refresh: Boolean(refresh) }),
  aiLibrary: () => ipcRenderer.invoke("ai:library"),
  aiMessages: (chatId) => ipcRenderer.invoke("ai:messages", { chatId }),
  aiLibraryAction: (action) => ipcRenderer.invoke("ai:library-action", action),
  aiChat: (payload) => ipcRenderer.invoke("ai:chat", payload),
  aiAbort: (requestId) => ipcRenderer.invoke("ai:abort", { requestId }),
  onAiDelta: subscribe("agzos:ai-delta"),
  onAiLibrary: subscribe("agzos:ai-library"),
  tabSelection: (id) => ipcRenderer.invoke("tab:selection", { id }),
  terminalAvailable: () => ipcRenderer.invoke("terminal:available"),
  terminalOpen: (options) => ipcRenderer.invoke("terminal:open", options ?? {}),
  terminalWrite: (id, data) => ipcRenderer.send("terminal:write", { id, data }),
  terminalResize: (id, cols, rows) => ipcRenderer.invoke("terminal:resize", { id, cols, rows }),
  terminalKill: (id) => ipcRenderer.invoke("terminal:kill", { id }),
  terminalFocus: (focused) => ipcRenderer.invoke("terminal:focus", { focused }),
  terminalSaved: () => ipcRenderer.invoke("terminal:saved"),
  terminalSave: (list) => ipcRenderer.invoke("terminal:save", list),
  terminalList: () => ipcRenderer.invoke("terminal:list"),
  terminalOpenSsh: (connection, cols, rows) =>
    ipcRenderer.invoke("terminal:open-ssh", { connection, cols, rows }),
  terminalConfig: (config) => ipcRenderer.invoke("terminal:config", config),
  terminalConfigGet: () => ipcRenderer.invoke("terminal:config-get"),
  terminalPip: (open) => ipcRenderer.invoke("terminal:pip", { open }),
  terminalDock: (dock) => ipcRenderer.invoke("terminal:dock", { dock }),
  terminalTools: (commands) => ipcRenderer.invoke("terminal:tools", { commands }),
  terminalSecrets: () => ipcRenderer.invoke("terminal:secrets"),
  terminalSecretSet: (name, value) => ipcRenderer.invoke("terminal:secret-set", { name, value }),
  terminalSecretRemove: (name) => ipcRenderer.invoke("terminal:secret-remove", { name }),
  sshKeys: () => ipcRenderer.invoke("ssh:keys"),
  sshGenerate: (options) => ipcRenderer.invoke("ssh:generate", options),
  aiTranscribe: (audio, mime, language) =>
    ipcRenderer.invoke("ai:transcribe", { audio, mime, language }),
  micAccess: () => ipcRenderer.invoke("media:mic-access"),
  onTerminalConfig: subscribe("agzos:terminal-config"),
  onTerminalPip: subscribe("agzos:terminal-pip"),
  clipboardRead: () => ipcRenderer.invoke("terminal:clipboard-read"),
  clipboardWrite: (text) => ipcRenderer.invoke("terminal:clipboard-write", { text }),
  onTerminalData: subscribe("agzos:terminal-data"),
  onTerminalExit: subscribe("agzos:terminal-exit"),
  onTerminalCwd: subscribe("agzos:terminal-cwd"),
  // 4.1.1
  terminalRename: (id, title) => ipcRenderer.invoke("terminal:rename", { id, title }),
  onTerminalTitle: subscribe("agzos:terminal-title"),
  terminalInstallTools: (ids, cols, rows) =>
    ipcRenderer.invoke("terminal:install-tools", { ids, cols, rows }),
  terminalOpenAgent: (options) => ipcRenderer.invoke("terminal:open-agent", options ?? {}),
  terminalSkills: (cwd) => ipcRenderer.invoke("terminal:skills", { cwd }),
  terminalSkillCreate: (options) => ipcRenderer.invoke("terminal:skill-create", options ?? {}),
  agentGroq: (prompt) => ipcRenderer.invoke("agent:groq", { prompt }),
  agentPlan: (goal, tools) => ipcRenderer.invoke("agent:plan", { goal, tools }),
  filesList: (dir, hidden) => ipcRenderer.invoke("files:list", { dir, hidden }),
  filesHome: () => ipcRenderer.invoke("files:home"),
  filesOpen: (file, where) => ipcRenderer.invoke("files:open", { file, where }),
  filesPick: () => ipcRenderer.invoke("files:pick"),
  pwaState: (tabId) => ipcRenderer.invoke("pwa:state", { tabId }),
  pwaCheck: (tabId) => ipcRenderer.invoke("pwa:check", { tabId }),
  pwaInstall: (tabId) => ipcRenderer.invoke("pwa:install", { tabId }),
  pwaOpen: (id) => ipcRenderer.invoke("pwa:open", { id }),
  pwaUninstall: (id) => ipcRenderer.invoke("pwa:uninstall", { id }),
  pwaList: () => ipcRenderer.invoke("pwa:list"),
  onPwaState: subscribe("agzos:pwa-state"),
  onPwaChanged: subscribe("agzos:pwa-changed"),
  gesturesConfig: (config) => ipcRenderer.invoke("gestures:config", config),
  gesture: (gesture) => ipcRenderer.send("agzos:gesture", { gesture }),
  onGesture: subscribe("agzos:gesture"),
  sidePanelNav: (app, action) => ipcRenderer.invoke("sidepanel:nav", { app, action }),
  gpuStatus: () => ipcRenderer.invoke("gpu:status"),
  gpuSet: (enabled) => ipcRenderer.invoke("gpu:set", { enabled }),
  allowCertificate: (id) => ipcRenderer.invoke("certificate:allow", { id }),
  windowStartup: () => ipcRenderer.invoke("window:startup"),
  whatsNew: () => ipcRenderer.invoke("app:whats-new"),
  appVersion: () => ipcRenderer.invoke("app:version"),
  onStateSync: subscribe("agzos:state-sync"),
  onUpdate: subscribe("agzos:update"),
  onTabEvent: subscribe("agzos:tab-event"),
  onOpenRequest: subscribe("agzos:open-request"),
  onFullscreen: subscribe("agzos:fullscreen"),
  onHotkey: subscribe("agzos:hotkey"),
  onTabMenuAction: subscribe("agzos:tabmenu-action"),
  onRequestPermission: subscribe("agzos:permission-request"),
  onDownload: subscribe("agzos:download"),
  onModifierUp: subscribe("agzos:modifier-up"),
  showTabPreview: (payload) => ipcRenderer.invoke("preview:show", payload),
  hideTabPreview: () => ipcRenderer.invoke("preview:hide"),
  renderSwitcher: (model) => ipcRenderer.invoke("switcher:render", model),
  setSwitcherOpen: (open) => ipcRenderer.invoke("switcher:state", { open }),
  onSwitcherKey: subscribe("agzos:switcher-key"),
  onAdblockStats: subscribe("agzos:adblock-stats"),
  overlayOpen: (payload) => ipcRenderer.invoke("overlay:open", payload),
  overlayClose: () => ipcRenderer.invoke("overlay:close"),
  overlayReply: (id, result) => ipcRenderer.invoke("overlay:reply", { id, result }),
  onOverlayCall: subscribe("agzos:overlay-call"),
  onOverlayDismissed: subscribe("agzos:overlay-dismissed"),
  // 4.5
  sidePanelExpand: (expanded) => ipcRenderer.invoke("sidepanel:expand", { expanded }),
  tabCover: (id, covered) => ipcRenderer.invoke("tab:cover", { id, covered }),
  portsList: () => ipcRenderer.invoke("ports:list"),
  portsKill: (pid) => ipcRenderer.invoke("ports:kill", { pid }),
  tunnelStatus: () => ipcRenderer.invoke("tunnel:status"),
  tunnelStart: (port) => ipcRenderer.invoke("tunnel:start", { port }),
  tunnelStop: (port) => ipcRenderer.invoke("tunnel:stop", { port }),
  tunnelPickBinary: () => ipcRenderer.invoke("tunnel:pick-binary"),
  onTunnel: subscribe("agzos:tunnel"),
  inspectorToggle: (id) => ipcRenderer.invoke("inspector:toggle", { id }),
  readerExtract: (id) => ipcRenderer.invoke("reader:extract", { id }),
  captureTake: (mode) => ipcRenderer.invoke("capture:take", { mode }),
  captureCopy: (dataUrl) => ipcRenderer.invoke("capture:copy", { dataUrl }),
  captureSave: (dataUrl) => ipcRenderer.invoke("capture:save", { dataUrl }),
  scratchpadCapture: (id, on) => ipcRenderer.invoke("scratchpad:capture", { id, on }),
  scratchpadSend: (request, tabId) => ipcRenderer.invoke("scratchpad:send", { request, tabId }),
  onNetCapture: subscribe("agzos:net-capture"),
  extensionsList: () => ipcRenderer.invoke("extensions:list"),
  extensionsAddUnpacked: () => ipcRenderer.invoke("extensions:add-unpacked"),
  extensionsInstallStore: (input) => ipcRenderer.invoke("extensions:install-store", { input }),
  extensionsSetEnabled: (dir, enabled) =>
    ipcRenderer.invoke("extensions:set-enabled", { dir, enabled }),
  extensionsReload: (dir) => ipcRenderer.invoke("extensions:reload", { dir }),
  extensionsRemove: (dir) => ipcRenderer.invoke("extensions:remove", { dir }),
  widevineStatus: () => ipcRenderer.invoke("widevine:status"),
});
